export const DEFAULT_COUNTRY = 'DEFAULT_COUNTRY';

export const GET_PAGE_TITLE = "GET_PAGE_TITLE"

export const GET_WORLD_COUNTRIES_REQUEST = "GET_WORLD_COUNTRIES_REQUEST"
export const GET_WORLD_COUNTRIES_SUCCESS = "GET_WORLD_COUNTRIES_SUCCESS"
export const GET_WORLD_COUNTRIES_ERROR = "GET_WORLD_COUNTRIES_ERROR"

export const GET_COUNTRY_DATA_REQUEST = "GET_COUNTRY_DATA_REQUEST"
export const GET_COUNTRY_DATA_SUCCESS = "GET_COUNTRY_DATA_SUCCESS"
export const GET_COUNTRY_DATA_ERROR = "GET_COUNTRY_DATA_ERROR"

export const GET_COUNTRY_HISTORICAL_REQUEST = "GET_COUNTRY_HISTORICAL_REQUEST"
export const GET_COUNTRY_HISTORICAL_SUCCESS = "GET_COUNTRY_HISTORICAL_SUCCESS"
export const GET_COUNTRY_HISTORICAL_ERROR = "GET_COUNTRY_HISTORICAL_ERROR"

export const GET_COUNTRY_VACCINATION_REQUEST = "GET_COUNTRY_VACCINATION_REQUEST"
export const GET_COUNTRY_VACCINATION_SUCCESS = "GET_COUNTRY_VACCINATION_SUCCESS"
export const GET_COUNTRY_VACCINATION_ERROR = "GET_COUNTRY_VACCINATION_ERROR"

